services:
  anichan:
    build: .
    image: anichan:latest
    container_name: anichan
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - anichan-data:/app/data
    # environment:
    #   - BOT_TOKEN=Your bot token here
    #   - CLIENT_ID=Your client id here
    #   - API_URL=https://graphql.anilist.co

volumes:
  anichan-data: